### ISSUE TITLE
no module named 'imp'

### ISSUE THREAD

**Issue by veitch123** [omine-me/LaughterSegmentation#2]
`Collecting audioread==3.0.0 (from -r requirements.txt (line 15))
  Using cached audioread-3.0.0.tar.gz (377 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/xt/yb5btvp501ngl71d59j030840000gp/T/pip-install-mkr1aw5o/audioread_88bf52e368d24a36a5be9fb6eb2ca323/setup.py", line 17, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by veitch123** [comment]
Apparently this is because "imp is deprecated and is turned into importlib in 3.12."

[https://github.com/BradenM/micropy-cli/issues/575#](url)

**Comment by omine-me** [comment]
Thank you for sharing that Python<=3.11 is recommended.
