### ISSUE TITLE
how to synthesize laugh data?

### ISSUE THREAD

**Issue by TitaniumTTL** [omine-me/LaughterSegmentation#4]
It is a significant work. can I ask to how to synthesize laugh data?

**Comment by omine-me** [comment]
Thank you for your interest.
It's in the paper but it's not published yet, so here's a link to the paper pdf.
[Robust Laughter Segmentation with Automatic Diverse Data Synthesis](https://drive.google.com/file/d/1WqYKGvCC3b-l8zN06ESh8GlcqJyC9hLm/view?usp=sharing)
